set_property SRC_FILE_INFO {cfile:/home/nfant/vc-standalone/vc_standalone/vc_standalone.srcs/constrs_1/new/constr.xdc rfile:../../../vc_standalone.srcs/constrs_1/new/constr.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E3  IOSTANDARD LVCMOS33} [get_ports {clk}]; #IO_L12P_T1_MRCC_35 Sch=gclk[100]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D9    IOSTANDARD LVCMOS33 } [get_ports { rst }]; #IO_L6N_T0_VREF_16 Sch=btn[0]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E15 IOSTANDARD TMDS_33  } [get_ports { ch2_p}]; #IO_L12P_T1_MRCC_15 Sch=jb[1]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E16 IOSTANDARD TMDS_33  } [get_ports { ch2_n}]; #IO_L12N_T1_MRCC_15 Sch=jb[2]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D15 IOSTANDARD TMDS_33  } [get_ports { ch1_p}]; #IO_L22N_T3_A16_15 Sch=jb[3]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C15 IOSTANDARD TMDS_33 } [get_ports { ch1_n}]; #IO_L23P_T3_FOE_B_15 Sch=jb[4]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J17 IOSTANDARD TMDS_33} [get_ports { ch0_p}]; #IO_L23N_T3_FWE_B_15 Sch=jb[7]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J18 IOSTANDARD TMDS_33   } [get_ports { ch0_n }]; #IO_L24P_T3_RS1_15 Sch=jb[8]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K15 IOSTANDARD TMDS_33  } [get_ports { chc_p}]; #IO_L24N_T3_RS0_15 Sch=jb[9]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J15 IOSTANDARD TMDS_33  } [get_ports { chc_n}]; #IO_25_15 Sch=jb[10]
